# MCMC Paramters
mcmc: 
  nwalkers: 100
  nsteps: 5000
  backend_path: ./output/backend_20231101t1541.hdf
  merit:
    ftn: uniform
    args:
      lower_bound: 0.0
      upper_bound: 30.0

  variables:
    idark: 
      prior_ftn: [uniform]  # Must be a list
      prior_args:
        lower_bound: [1.0e-6]
        upper_bound: [1.0e-4]
      ini_pars: 
        center: [1.0e-5] 
        spread: [1.0e-7] 
    wfsc_factor: 
      prior_ftn:
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
      prior_args: 
        lower_bound:    
          - [1.0E-7, 1.0E-3, .NAN, .NAN]
          - [1.0E-7, 1.0E-3, .NAN, .NAN]
          - [1.0E-7, 1.0E-3, .NAN, .NAN]
          - [1.0E-7, 1.0E-3, .NAN, .NAN]
          - [1.0E-7, 1.0E-3, .NAN, .NAN]
          - [1.0E-7, 1.0E-3, .NAN, .NAN]
        upper_bound:
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
      ini_pars: 
        center: 
          # Center values for initializing walkers
          - [5.0E-7, 5.0E-3, .NAN, .NAN]
          - [5.0E-7, 5.0E-3, .NAN, .NAN]
          - [5.0E-7, 5.0E-3, .NAN, .NAN]
          - [5.0E-7, 5.0E-3, .NAN, .NAN]
          - [5.0E-7, 5.0E-3, .NAN, .NAN]
          - [5.0E-7, 5.0E-3, .NAN, .NAN]
        spread: 
          # Spread for initializing walkers
          - [1.0E-8, 1.0E-4, .NAN, .NAN]
          - [1.0E-8, 1.0E-4, .NAN, .NAN]
          - [1.0E-8, 1.0E-4, .NAN, .NAN]
          - [1.0E-8, 1.0E-4, .NAN, .NAN]
          - [1.0E-8, 1.0E-4, .NAN, .NAN]
          - [1.0E-8, 1.0E-4, .NAN, .NAN]
    contrast:  # raw contrast
      prior_ftn:
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
      prior_args:
        lower_bound:
          - 5.0e-11
          - 5.0e-11
          - 5.0e-11
          - 5.0e-11
          - 5.0e-11
          - 5.0e-11
        upper_bound:
          - 5.0e-10
          - 5.0e-10
          - 5.0e-10
          - 5.0e-10
          - 5.0e-10
          - 5.0e-10
      ini_pars:
        center:
          - 1.000000000000000311e-10
          - 1.000000000000000311e-10
          - 1.000000000000000311e-10
          - 1.000000000000000311e-10
          - 1.000000000000000311e-10
          - 1.000000000000000311e-10
        spread:
          - 2.000000000000000311e-12
          - 2.000000000000000311e-12
          - 2.000000000000000311e-12
          - 2.000000000000000311e-12
          - 2.000000000000000311e-12
          - 2.000000000000000311e-12
    throughput:  # core throughput
      prior_ftn:
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
      prior_args:
        lower_bound:
          - 0.05
          - 0.05
          - 0.05
          - 0.05
          - 0.05
          - 0.05
        upper_bound:
          - 0.5
          - 0.5
          - 0.5
          - 0.5
          - 0.5
          - 0.5
      ini_pars:
        center:
          - 0.15
          - 0.15
          - 0.15
          - 0.15
          - 0.15
          - 0.15
        spread:
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
      
        - uniform
        - uniform
        - uniform
      prior_args:
        lower_bound:
          - 0.03
          - 0.03
          - 0.03
          - 0.03
          - 0.03
          - 0.03
        upper_bound:
          - 0.3
          - 0.3
          - 0.3
          - 0.3
          - 0.3
          - 0.3
      ini_pars:
        center:
          - 0.15
          - 0.15
          - 0.15
          - 0.15
          - 0.15
          - 0.15
        spread:
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
      
# Initial argument values for ebs.ErrorBudget.run_etc()

paths:
  output: ./output
  input: ./inputs

input_files:
  contrast: mcmc_contrast.csv
  throughput: mcmc_throughput.csv
  wfe: mcmc_wfe.csv
  wfsc_factor: mcmc_wfsc.csv
  sensitivity: mcmc_sensitivity.csv

#json_files:
#  ref_json: mcmc_ref.json  # An input specifiying the 'unaberrated' observatory
#  pp_json: mcmc_pp.json  # An intermediate file read in by EXOSIMS

targets:
  star1:
    HIP: 32439 A
    spec_type: F8V
    luminosity: 0.2615
    eeid: 0.07423
    eepsr: 6.34e-11
    exo_zodi: 3.0
  star2:
    HIP: 77052 A
    spec_type: G5V
    luminosity: -0.0788
    eeid: 0.06174
    eepsr: 1.39e-10
    exo_zodi: 3.0
  star3:
    HIP: 79672 
    spec_type: G2Va
    luminosity: 0.0391
    eeid: 0.07399
    eepsr: 1.06e-10
    exo_zodi: 3.0
  star4:
    HIP: 26779 
    spec_type: K1V
    luminosity: -0.3209
    eeid: 0.05633
    eepsr: 2.42e-10
    exo_zodi: 3.0
  star5:
    HIP: 113283
    spec_type: K4Ve
    luminosity: -0.70
    eeid: 0.05829
    eepsr: 5.89e-10
    exo_zodi: 3.0
    

initial_exosims: 
    skipSaturationCalcs: true
    filterBinaries: false
    keepStarCatalog: true
    minComp: 0
    modules:
      BackgroundSources: ' '
# MCMC Paramters
mcmc: 
  nwalkers: 100
  nsteps: 5000
  backend_path: ./output/backend_20231101t1541.hdf
  merit:
    ftn: uniform
    args:
      lower_bound: 0.0
      upper_bound: 30.0

  variables:
    idark: 
      prior_ftn: [uniform]  # Must be a list
      prior_args:
        lower_bound: [1.0e-6]
