# MCMC Paramters
mcmc: 
  nwalkers: 4
  nsteps: 10000
  backend_path: ./outputs/backend_20231115t1006.hdf
  merit:
    ftn: inverse_bounded
    args:
      lower_bound: 3.5E-5
      upper_bound: 83.3

  variables:
    idark: 
      prior_ftn: [uniform]  # Must be a list
      prior_args:
        lower_bound: [1.0e-6]
        upper_bound: [1.0e-4]
      ini_pars: 
        center: [1.0e-5] 
        spread: [1.0e-7] 
#    wfsc_factor: 
#      prior_ftn:
#        - [uniform, uniform, .NAN, .NAN]
#        - [uniform, uniform, .NAN, .NAN]
#        - [uniform, uniform, .NAN, .NAN]
#        - [uniform, uniform, .NAN, .NAN]
#        - [uniform, uniform, .NAN, .NAN]
#        - [uniform, uniform, .NAN, .NAN]
#      prior_args: 
#        lower_bound:    
#          - [1.0E-7, 1.0E-3, .NAN, .NAN]
#          - [1.0E-7, 1.0E-3, .NAN, .NAN]
#          - [1.0E-7, 1.0E-3, .NAN, .NAN]
#          - [1.0E-7, 1.0E-3, .NAN, .NAN]
#          - [1.0E-7, 1.0E-3, .NAN, .NAN]
#          - [1.0E-7, 1.0E-3, .NAN, .NAN]
#        upper_bound:
#          - [1.0, 1.0, .NAN, .NAN]
#          - [1.0, 1.0, .NAN, .NAN]
#          - [1.0, 1.0, .NAN, .NAN]
#          - [1.0, 1.0, .NAN, .NAN]
#          - [1.0, 1.0, .NAN, .NAN]
#          - [1.0, 1.0, .NAN, .NAN]
#      ini_pars: 
#        center: 
#          # Center values for initializing walkers
#          - [5.0E-6, 5.0E-3, .NAN, .NAN]
#          - [5.0E-6, 5.0E-3, .NAN, .NAN]
#          - [1.0E-5, 5.0E-3, .NAN, .NAN]
#          - [1.0E-4, 5.0E-3, .NAN, .NAN]
#          - [2.0E-4, 5.0E-3, .NAN, .NAN]
#          - [2.0E-3, 5.0E-2, .NAN, .NAN]
#        spread: 
#          # Spread for initializing walkers
#          - [1.0E-8, 1.0E-4, .NAN, .NAN]
#          - [1.0E-8, 1.0E-4, .NAN, .NAN]
#          - [1.0E-8, 1.0E-4, .NAN, .NAN]
#          - [1.0E-8, 1.0E-4, .NAN, .NAN]
#          - [1.0E-8, 1.0E-4, .NAN, .NAN]
#          - [1.0E-8, 1.0E-4, .NAN, .NAN]
    contrast:  # raw contrast
      prior_ftn:
        - .NAN
        - .NAN
        - uniform
        - .NAN
        - .NAN
        - .NAN
      prior_args:
        lower_bound:
          - .NAN
          - .NAN
          - 1.0e-10
          - .NAN
          - .NAN
          - .NAN
        upper_bound:
          - .NAN
          - .NAN
          - 1.0e-9
          - .NAN
          - .NAN
          - .NAN
      ini_pars:
        center:
          - .NAN
          - .NAN
          - 1.500000000000000311e-10
          - .NAN
          - .NAN
          - .NAN
        spread:
          - .NAN
          - .NAN
          - 2.000000000000000311e-12
          - .NAN
          - .NAN
          - .NAN
#    throughput:  # core throughput
#      prior_ftn:
#        - .NAN
#        - .NAN 
#        - uniform
#        - uniform
#        - uniform
#        - .NAN 
#      prior_args:
#        lower_bound:
#          - .NAN
#          - .NAN
#          - 0.03
#          - 0.03
#          - 0.03
#          - .NAN
#        upper_bound:
#          - .NAN
#          - .NAN
#          - 0.3
#          - 0.3
#          - 0.3
#          - .NAN
#      ini_pars:
#        center:
#          - .NAN
#          - .NAN
#          - 0.15
#          - 0.15
#          - 0.15
#          - .NAN
#        spread:
#          - .NAN
#          - .NAN
#          - 0.0015
#          - 0.0015
#          - 0.0015
#          - .NAN
      
# Initial argument values for ebs.ErrorBudget.run_etc()

paths:
  output: ./outputs
  input: ./inputs

input_files:
  contrast: mcmc_contrast.csv
  throughput: mcmc_throughput.csv
  wfe: mcmc_wfe.csv
  wfsc_factor: mcmc_wfsc.csv
  sensitivity: mcmc_sensitivity.csv

#json_files:
#  ref_json: mcmc_ref.json  # An input specifiying the 'unaberrated' observatory
#  pp_json: mcmc_pp.json  # An intermediate file read in by EXOSIMS

targets:
#  star1:
#    HIP: 32439 A
#    spec_type: F8V
#    luminosity: 0.2615
#    eeid: 0.07423
#    eepsr: 6.34e-11
#    exo_zodi: 3.0
#  star2:
#    HIP: 77052 A
#    spec_type: G5V
#    luminosity: -0.0788
#    eeid: 0.06174
#    eepsr: 1.39e-10
#    exo_zodi: 3.0
  star3:
    HIP: 79672 
    spec_type: G2Va
    luminosity: 0.0391
    eeid: 0.07399
    eepsr: 1.06e-10
    exo_zodi: 3.0
#  star4:
#    HIP: 26779 
#    spec_type: K1V
#    luminosity: -0.3209
#    eeid: 0.05633
#    eepsr: 2.42e-10
#    exo_zodi: 3.0
#  star5:
#    HIP: 113283
#    spec_type: K4Ve
#    luminosity: -0.70
#    eeid: 0.05829
#    eepsr: 5.89e-10
#    exo_zodi: 3.0
    

initial_exosims: 
    skipSaturationCalcs: true
    filterBinaries: false
    keepStarCatalog: true
    minComp: 0
    modules:
      BackgroundSources: ' '
      Completeness: ' '
      Observatory: ' '
      OpticalSystem: Nemati
      PlanetPhysicalModel: ' '
      PlanetPopulation: ' '
      PostProcessing: ' '
      SimulatedUniverse: ' '
      StarCatalog: HWOMissionStars
      SurveyEnsemble: ' '
      SurveySimulation: ' '
      TargetList: ' '
      TimeKeeping: ' '
      ZodiacalLight: ' '
    obscurFac: 0.01
    observingModes:
    - SNR: 5.0
      detectionMode: true
      instName: CONS_NF_Imager
      systName: coronagraph-550
      timeMultiplier: 1.0
#    ppFact: 0.01
    pupilDiam: 6.52  # USORT enscribed diameter
    scienceInstruments:
    - CIC: 0.0021  # Ref Roman_Coronagraph_ETC
      ENF: 1.0  # Parameter specific to EMCCDs
      FoV: 9.5
      QE: 0.835  # ibid
      idark: 3.0e-05  # ibid
      name: CONS_NF_Imager
      optics: 0.85
      pixelNumber: 1024
      pixelScale: 0.00928 # derived from FoV and pixelNumber
      pixelSize: 1.3e-05  # ibid
      sread: 1.7e-06  # ibid
      texp: 3  # ibid
#      Rs: 140  # parameter specific to spectrometers
#      lensSamp: 4  # parameter specific to spectrometers
    starlightSuppressionSystems:
    - BW: 0.2
      IWA: 0.05
      OWA: 0.5
      core_area: 0.000552
#      core_contrast: ./test/test_contrast.csv
#      core_thruput: ./test/test_throughput.csv
      lam: 550.0
      name: coronagraph-550
      occ_trans: 0.4  # Rough estimate from Roman Coronagraph ETC
      occulter: false
      optics: 0.39  # 2 reflections @ 0.92, 13 reflections @ 0.98, 0.60 
                    # in-band transmission at the photometric filter (EXO-C)
