paths:
  output: ./output
  input: ./inputs

num_spatial_modes: 13
num_temporal_modes: 6
angles:
  num_angles: 5
  start: 0.055 # as
  stop: 0.5 # as

iter_parameters:
  contrasts: [1.0e-10, 2.0e-10, 5.0e-10]
  throughputs: [0.08, 0.16, 0.32]
  dark_currents: [1.5e-5, 3.0e-5, 6.0e-5]
  iwas: [0.05, 0.07, 0.09]

input_files:
  contrast: example_contrast.csv
  throughput: example_throughput.csv

json_files:
  ref_json: example_ref.json
  pp_json: example_pp.json

targets:
  star1:
    HIP: 32439
    spec_type: F8V
    luminosity: 0.2615
    eeid: 0.07423
    eepsr: 6.34e-11
    exo_zodi: 3.0
  star2:
    HIP: 77052
    spec_type: G5V
    luminosity: -0.0788
    eeid: 0.06174
    eepsr: 1.39e-10
    exo_zodi: 3.0
  star3:
    HIP: 79672
    spec_type: G2Va
    luminosity: 0.0391
    eeid: 0.07399
    eepsr: 1.06e-10
    exo_zodi: 3.0
  star4:
    HIP: 26779
    spec_type: K1V
    luminosity: -0.3209
    eeid: 0.05633
    eepsr: 2.42e-10
    exo_zodi: 3.0
  star5:
    HIP: 113283
    spec_type: K4Ve
    luminosity: -0.70
    eeid: 0.05829
    eepsr: 5.89e-10
    exo_zodi: 3.0


