paths:
  output: ./output
  input: ./inputs
  temporary: ./temp

input_files:
  contrast: baseline_contrast.csv
  throughput: baseline_throughput.csv
  wfe: baseline_wfe.csv
  wfsc: baseline_wfsc.csv
  sensitivity: baseline_sensitivity.csv

json_file: example_ref.json  # An input specifying the 'unaberrated' observatory

# iter_values: [1.0e-10, 5.0e-5]
iter_values: [0.1, 1.0]

working_angles:  # In units of EEID (which is target dependent).
  # HZ is defined as (0.95 - 1.67)*EEID
  - 0.95
  - 1.35
  - 1.67

targets:
  star1:
    HIP: 32439 A
    spec_type: F8V
    luminosity: 0.2615
    eeid: 0.07423
    eepsr: 6.34e-11
    exo_zodi: 3.0
  star2:
    HIP: 77052 A
    spec_type: G5V
    luminosity: -0.0788
    eeid: 0.06174
    eepsr: 1.39e-10
    exo_zodi: 3.0
  star3:
    HIP: 79672 
    spec_type: G2Va
    luminosity: 0.0391
    eeid: 0.07399
    eepsr: 1.06e-10
    exo_zodi: 3.0
  star4:
    HIP: 26779
    spec_type: K1V
    luminosity: -0.3209
    eeid: 0.05633
    eepsr: 2.42e-10
    exo_zodi: 3.0
  star5:
    HIP: 113283
    spec_type: K4Ve
    luminosity: -0.70
    eeid: 0.05829
    eepsr: 5.89e-10
    exo_zodi: 3.0

plotting:
  force_linear: false
  plot_stars: [26779, 113283] # only plot K stars
  fill: true
  plot_by_spectype: true


# MCMC Parameters
mcmc:
  parallel: true  # True: multiprocess. False: single process
  save: false  # Automatically save key I/O files for the run
  new_run: true  # If false, <save> above must be set to true.
                  # If false, the run is a contiuation of a previous run,
                  # and the user must specify below the full path to the
                  # emcee.Backend file.
  previous_backend_path: ./outputs/saved_run_20231204t172750/backend.hdf
#  previous_backend_: null
  nwalkers: 46
  nsteps: 3
  merit:
    ftn: chi_square
    args:
      center: 3.0
      scale: 2.0

  variables:
    idark:
      prior_ftn: [uniform]  # Must be a list
      prior_args:
        lower_bound: [1.0e-6]
        upper_bound: [1.0e-4]
      ini_pars:
        center: [1.0e-5]
        spread: [1.0e-7]
    wfsc_factor:
      prior_ftn:
        - [.NAN, .NAN, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
        - [uniform, uniform, .NAN, .NAN]
      prior_args:
        lower_bound:
          - [.NAN, .NAN, .NAN, .NAN]
          - [1.0E-6, 1.0E-6, .NAN, .NAN]
          - [1.0E-6, 1.0E-6, .NAN, .NAN]
          - [1.0E-6, 1.0E-6, .NAN, .NAN]
          - [1.0E-6, 1.0E-6, .NAN, .NAN]
          - [1.0E-6, 1.0E-6, .NAN, .NAN]
        upper_bound:
          - [.NAN, .NAN, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
          - [1.0, 1.0, .NAN, .NAN]
      ini_pars:
        center:
          # Center values for initializing walkers
          - [.NAN, .NAN, .NAN, .NAN]
          - [1.0E-3, 1.0E-3, .NAN, .NAN]
          - [1.0E-3, 1.0E-3, .NAN, .NAN]
          - [1.0E-3, 5.0E-3, .NAN, .NAN]
          - [1.0E-3, 5.0E-3, .NAN, .NAN]
          - [1.0E-3, 5.0E-3, .NAN, .NAN]
        spread:
          # Spread for initializing walkers
          - [.NAN, .NAN, .NAN, .NAN]
          - [1.0E-4, 1.0E-4, .NAN, .NAN]
          - [1.0E-4, 1.0E-4, .NAN, .NAN]
          - [1.0E-4, 1.0E-4, .NAN, .NAN]
          - [1.0E-4, 1.0E-4, .NAN, .NAN]
          - [1.0E-4, 1.0E-4, .NAN, .NAN]
    contrast:  # raw contrast
      prior_ftn:
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
      prior_args:
        lower_bound:
          - 1.0e-11
          - 1.0e-11
          - 1.0e-11
          - 1.0e-11
          - 1.0e-11
          - 1.0e-11
        upper_bound:
          - 1.0e-9
          - 1.0e-9
          - 1.0e-9
          - 1.0e-9
          - 1.0e-9
          - 1.0e-9
      ini_pars:
        center:
          - 2.0e-11
          - 2.0e-11
          - 2.0e-11
          - 2.0e-11
          - 2.0e-11
          - 2.0e-11
        spread:
          - 2.0e-12
          - 2.0e-12
          - 2.0e-12
          - 2.0e-12
          - 2.0e-12
          - 2.0e-12
    throughput:  # core throughput
      prior_ftn:
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
        - uniform
      prior_args:
        lower_bound:
          - 0.01
          - 0.01
          - 0.01
          - 0.01
          - 0.01
          - 0.01
        upper_bound:
          - 0.6
          - 0.6
          - 0.6
          - 0.6
          - 0.6
          - 0.6
      ini_pars:
        center:
          - 0.15
          - 0.15
          - 0.15
          - 0.15
          - 0.15
          - 0.15
        spread:
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
          - 0.0015
